config/routes.rb
Rails.application.routes.draw do
  devise_for :podcasts
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podbuff</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if alert %>
        <p class="alert"><%= alert %></p>
    <% elsif notice %>
        <p class="notice"><%= notice %></p>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="background">
      <header>
        <div class="wrapper_wide">
           <a href="#" id="logo">PodBuff</a>
      <nav>
        <ul>
          <% unless podcast_signed_in? %>

          <li><a href="#">Explore</a></li>
          <li> <%= link_to "Sign In",  new_podcast_session_path %> </li>
          <li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
          <% else %>
          <li> <%= link_to "Sign Out", destroy_podcast_session_path, method: :delete %> </li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Explore</a></li>
          <% end %>
        </ul>
      </nav>
        </div>
      </header>
      <div class="wrapper_skinny">
          <h1>Discover your new favourite <br> podcast or create your own</h1>
          <%= link_to "Create a Podcast", new_podcast_registration_path,   class: "button button_highlight"%>
          <a href="#" class="button button_white">Explore</a>
      </div>
  </div>